"""your message

Revision ID: 64ed72c7ac21
Revises: a49e52d0800b
Create Date: 2024-10-05 12:42:20.725421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ed72c7ac21'
down_revision = 'a49e52d0800b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
