"""create messages table

Revision ID: a49e52d0800b
Revises: dc85d4e7c214
Create Date: 2024-10-05 12:41:11.534334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a49e52d0800b'
down_revision = 'dc85d4e7c214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
